---
name: "Metadata: Label Commenter"

on:
  #workflow_dispatch:
  #issues:
  #  types:
  #    - labeled
  #    - unlabeled
  #pull_request_target:
  #  types:
  #    - labeled
  #    - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    name: Label commenter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: master

      - uses: peaceiris/actions-label-commenter@f0dbbef043eb1b150b566db36b0bdc8b7f505579 # tag=v1
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
